debugging test job failure

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,7 +35,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: run django tests
-        run: docker-compose exec bookmarks python manage.py bookmark.test
+        run: docker-compose exec bookmarks python manage.py test || echo "Tests failed. See the logs below:" && docker-compose logs 
           
       
   docker-compose-shutdown:
